services:
  db:
    image: postgres:16
    container_name: eljopos-db
    environment:
      POSTGRES_USER: eljopos_user
      POSTGRES_PASSWORD: 123eljopos
      POSTGRES_DB: eljopos
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: